package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPoExample.Criteria;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPoExample.Criterion;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPoExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ExpressPoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    public String insertSelective(ExpressPo row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("freight_express");
        
        if (row.getBillCode() != null) {
            sql.VALUES("`bill_code`", "#{billCode,jdbcType=VARCHAR}");
        }
        
        if (row.getShopLogisticsId() != null) {
            sql.VALUES("`shop_logistics_id`", "#{shopLogisticsId,jdbcType=BIGINT}");
        }
        
        if (row.getSenderRegionId() != null) {
            sql.VALUES("`sender_region_id`", "#{senderRegionId,jdbcType=BIGINT}");
        }
        
        if (row.getSenderAddress() != null) {
            sql.VALUES("`sender_address`", "#{senderAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getDeliverRegionId() != null) {
            sql.VALUES("`deliver_region_id`", "#{deliverRegionId,jdbcType=BIGINT}");
        }
        
        if (row.getDeliverAddress() != null) {
            sql.VALUES("`deliver_address`", "#{deliverAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getSenderName() != null) {
            sql.VALUES("`sender_name`", "#{senderName,jdbcType=VARCHAR}");
        }
        
        if (row.getSenderMobile() != null) {
            sql.VALUES("`sender_mobile`", "#{senderMobile,jdbcType=VARCHAR}");
        }
        
        if (row.getDeliverName() != null) {
            sql.VALUES("`deliver_name`", "#{deliverName,jdbcType=VARCHAR}");
        }
        
        if (row.getStatus() != null) {
            sql.VALUES("`status`", "#{status,jdbcType=TINYINT}");
        }
        
        if (row.getShopId() != null) {
            sql.VALUES("`shop_id`", "#{shopId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.VALUES("`creator_id`", "#{creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.VALUES("`creator_name`", "#{creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.VALUES("`modifier_id`", "#{modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.VALUES("`modifier_name`", "#{modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.VALUES("`gmt_create`", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.VALUES("`gmt_modified`", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDeliverMobile() != null) {
            sql.VALUES("`deliver_mobile`", "#{deliverMobile,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    public String selectByExample(ExpressPoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`bill_code`");
        sql.SELECT("`shop_logistics_id`");
        sql.SELECT("`sender_region_id`");
        sql.SELECT("`sender_address`");
        sql.SELECT("`deliver_region_id`");
        sql.SELECT("`deliver_address`");
        sql.SELECT("`sender_name`");
        sql.SELECT("`sender_mobile`");
        sql.SELECT("`deliver_name`");
        sql.SELECT("`status`");
        sql.SELECT("`shop_id`");
        sql.SELECT("`creator_id`");
        sql.SELECT("`creator_name`");
        sql.SELECT("`modifier_id`");
        sql.SELECT("`modifier_name`");
        sql.SELECT("`gmt_create`");
        sql.SELECT("`gmt_modified`");
        sql.SELECT("`deliver_mobile`");
        sql.FROM("freight_express");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ExpressPo row = (ExpressPo) parameter.get("row");
        ExpressPoExample example = (ExpressPoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("freight_express");
        
        if (row.getId() != null) {
            sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        }
        
        if (row.getBillCode() != null) {
            sql.SET("`bill_code` = #{row.billCode,jdbcType=VARCHAR}");
        }
        
        if (row.getShopLogisticsId() != null) {
            sql.SET("`shop_logistics_id` = #{row.shopLogisticsId,jdbcType=BIGINT}");
        }
        
        if (row.getSenderRegionId() != null) {
            sql.SET("`sender_region_id` = #{row.senderRegionId,jdbcType=BIGINT}");
        }
        
        if (row.getSenderAddress() != null) {
            sql.SET("`sender_address` = #{row.senderAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getDeliverRegionId() != null) {
            sql.SET("`deliver_region_id` = #{row.deliverRegionId,jdbcType=BIGINT}");
        }
        
        if (row.getDeliverAddress() != null) {
            sql.SET("`deliver_address` = #{row.deliverAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getSenderName() != null) {
            sql.SET("`sender_name` = #{row.senderName,jdbcType=VARCHAR}");
        }
        
        if (row.getSenderMobile() != null) {
            sql.SET("`sender_mobile` = #{row.senderMobile,jdbcType=VARCHAR}");
        }
        
        if (row.getDeliverName() != null) {
            sql.SET("`deliver_name` = #{row.deliverName,jdbcType=VARCHAR}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("`status` = #{row.status,jdbcType=TINYINT}");
        }
        
        if (row.getShopId() != null) {
            sql.SET("`shop_id` = #{row.shopId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.SET("`creator_id` = #{row.creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.SET("`creator_name` = #{row.creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.SET("`modifier_id` = #{row.modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.SET("`modifier_name` = #{row.modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.SET("`gmt_create` = #{row.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.SET("`gmt_modified` = #{row.gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDeliverMobile() != null) {
            sql.SET("`deliver_mobile` = #{row.deliverMobile,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("freight_express");
        
        sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        sql.SET("`bill_code` = #{row.billCode,jdbcType=VARCHAR}");
        sql.SET("`shop_logistics_id` = #{row.shopLogisticsId,jdbcType=BIGINT}");
        sql.SET("`sender_region_id` = #{row.senderRegionId,jdbcType=BIGINT}");
        sql.SET("`sender_address` = #{row.senderAddress,jdbcType=VARCHAR}");
        sql.SET("`deliver_region_id` = #{row.deliverRegionId,jdbcType=BIGINT}");
        sql.SET("`deliver_address` = #{row.deliverAddress,jdbcType=VARCHAR}");
        sql.SET("`sender_name` = #{row.senderName,jdbcType=VARCHAR}");
        sql.SET("`sender_mobile` = #{row.senderMobile,jdbcType=VARCHAR}");
        sql.SET("`deliver_name` = #{row.deliverName,jdbcType=VARCHAR}");
        sql.SET("`status` = #{row.status,jdbcType=TINYINT}");
        sql.SET("`shop_id` = #{row.shopId,jdbcType=BIGINT}");
        sql.SET("`creator_id` = #{row.creatorId,jdbcType=BIGINT}");
        sql.SET("`creator_name` = #{row.creatorName,jdbcType=VARCHAR}");
        sql.SET("`modifier_id` = #{row.modifierId,jdbcType=BIGINT}");
        sql.SET("`modifier_name` = #{row.modifierName,jdbcType=VARCHAR}");
        sql.SET("`gmt_create` = #{row.gmtCreate,jdbcType=TIMESTAMP}");
        sql.SET("`gmt_modified` = #{row.gmtModified,jdbcType=TIMESTAMP}");
        sql.SET("`deliver_mobile` = #{row.deliverMobile,jdbcType=VARCHAR}");
        
        ExpressPoExample example = (ExpressPoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(ExpressPo row) {
        SQL sql = new SQL();
        sql.UPDATE("freight_express");
        
        if (row.getBillCode() != null) {
            sql.SET("`bill_code` = #{billCode,jdbcType=VARCHAR}");
        }
        
        if (row.getShopLogisticsId() != null) {
            sql.SET("`shop_logistics_id` = #{shopLogisticsId,jdbcType=BIGINT}");
        }
        
        if (row.getSenderRegionId() != null) {
            sql.SET("`sender_region_id` = #{senderRegionId,jdbcType=BIGINT}");
        }
        
        if (row.getSenderAddress() != null) {
            sql.SET("`sender_address` = #{senderAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getDeliverRegionId() != null) {
            sql.SET("`deliver_region_id` = #{deliverRegionId,jdbcType=BIGINT}");
        }
        
        if (row.getDeliverAddress() != null) {
            sql.SET("`deliver_address` = #{deliverAddress,jdbcType=VARCHAR}");
        }
        
        if (row.getSenderName() != null) {
            sql.SET("`sender_name` = #{senderName,jdbcType=VARCHAR}");
        }
        
        if (row.getSenderMobile() != null) {
            sql.SET("`sender_mobile` = #{senderMobile,jdbcType=VARCHAR}");
        }
        
        if (row.getDeliverName() != null) {
            sql.SET("`deliver_name` = #{deliverName,jdbcType=VARCHAR}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("`status` = #{status,jdbcType=TINYINT}");
        }
        
        if (row.getShopId() != null) {
            sql.SET("`shop_id` = #{shopId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.SET("`creator_id` = #{creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.SET("`creator_name` = #{creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.SET("`modifier_id` = #{modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.SET("`modifier_name` = #{modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.SET("`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.SET("`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDeliverMobile() != null) {
            sql.SET("`deliver_mobile` = #{deliverMobile,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, ExpressPoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}