package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ExpressPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @Delete({
        "delete from freight_express",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @Insert({
        "insert into freight_express (`bill_code`, `shop_logistics_id`, ",
        "`sender_region_id`, `sender_address`, ",
        "`deliver_region_id`, `deliver_address`, ",
        "`sender_name`, `sender_mobile`, ",
        "`deliver_name`, `status`, ",
        "`shop_id`, `creator_id`, ",
        "`creator_name`, `modifier_id`, ",
        "`modifier_name`, `gmt_create`, ",
        "`gmt_modified`, `deliver_mobile`)",
        "values (#{billCode,jdbcType=VARCHAR}, #{shopLogisticsId,jdbcType=BIGINT}, ",
        "#{senderRegionId,jdbcType=BIGINT}, #{senderAddress,jdbcType=VARCHAR}, ",
        "#{deliverRegionId,jdbcType=BIGINT}, #{deliverAddress,jdbcType=VARCHAR}, ",
        "#{senderName,jdbcType=VARCHAR}, #{senderMobile,jdbcType=VARCHAR}, ",
        "#{deliverName,jdbcType=VARCHAR}, #{status,jdbcType=TINYINT}, ",
        "#{shopId,jdbcType=BIGINT}, #{creatorId,jdbcType=BIGINT}, ",
        "#{creatorName,jdbcType=VARCHAR}, #{modifierId,jdbcType=BIGINT}, ",
        "#{modifierName,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtModified,jdbcType=TIMESTAMP}, #{deliverMobile,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ExpressPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @InsertProvider(type=ExpressPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(ExpressPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @SelectProvider(type=ExpressPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="bill_code", property="billCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_logistics_id", property="shopLogisticsId", jdbcType=JdbcType.BIGINT),
        @Result(column="sender_region_id", property="senderRegionId", jdbcType=JdbcType.BIGINT),
        @Result(column="sender_address", property="senderAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="deliver_region_id", property="deliverRegionId", jdbcType=JdbcType.BIGINT),
        @Result(column="deliver_address", property="deliverAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="sender_name", property="senderName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sender_mobile", property="senderMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="deliver_name", property="deliverName", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deliver_mobile", property="deliverMobile", jdbcType=JdbcType.VARCHAR)
    })
    List<ExpressPo> selectByExample(ExpressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `bill_code`, `shop_logistics_id`, `sender_region_id`, `sender_address`, ",
        "`deliver_region_id`, `deliver_address`, `sender_name`, `sender_mobile`, `deliver_name`, ",
        "`status`, `shop_id`, `creator_id`, `creator_name`, `modifier_id`, `modifier_name`, ",
        "`gmt_create`, `gmt_modified`, `deliver_mobile`",
        "from freight_express",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="bill_code", property="billCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_logistics_id", property="shopLogisticsId", jdbcType=JdbcType.BIGINT),
        @Result(column="sender_region_id", property="senderRegionId", jdbcType=JdbcType.BIGINT),
        @Result(column="sender_address", property="senderAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="deliver_region_id", property="deliverRegionId", jdbcType=JdbcType.BIGINT),
        @Result(column="deliver_address", property="deliverAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="sender_name", property="senderName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sender_mobile", property="senderMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="deliver_name", property="deliverName", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deliver_mobile", property="deliverMobile", jdbcType=JdbcType.VARCHAR)
    })
    ExpressPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ExpressPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") ExpressPo row, @Param("example") ExpressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ExpressPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") ExpressPo row, @Param("example") ExpressPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ExpressPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ExpressPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbg.generated
     */
    @Update({
        "update freight_express",
        "set `bill_code` = #{billCode,jdbcType=VARCHAR},",
          "`shop_logistics_id` = #{shopLogisticsId,jdbcType=BIGINT},",
          "`sender_region_id` = #{senderRegionId,jdbcType=BIGINT},",
          "`sender_address` = #{senderAddress,jdbcType=VARCHAR},",
          "`deliver_region_id` = #{deliverRegionId,jdbcType=BIGINT},",
          "`deliver_address` = #{deliverAddress,jdbcType=VARCHAR},",
          "`sender_name` = #{senderName,jdbcType=VARCHAR},",
          "`sender_mobile` = #{senderMobile,jdbcType=VARCHAR},",
          "`deliver_name` = #{deliverName,jdbcType=VARCHAR},",
          "`status` = #{status,jdbcType=TINYINT},",
          "`shop_id` = #{shopId,jdbcType=BIGINT},",
          "`creator_id` = #{creatorId,jdbcType=BIGINT},",
          "`creator_name` = #{creatorName,jdbcType=VARCHAR},",
          "`modifier_id` = #{modifierId,jdbcType=BIGINT},",
          "`modifier_name` = #{modifierName,jdbcType=VARCHAR},",
          "`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP},",
          "`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP},",
          "`deliver_mobile` = #{deliverMobile,jdbcType=VARCHAR}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ExpressPo row);
}