package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.WarehousePo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.WarehousePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WarehousePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @Delete({
        "delete from freight_warehouse",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @Insert({
        "insert into freight_warehouse (`address`, `shop_id`, ",
        "`name`, `sender_name`, ",
        "`creator_id`, `creator_name`, ",
        "`modifier_id`, `modifier_name`, ",
        "`gmt_create`, `gmt_modified`, ",
        "`region_id`, `sender_mobile`, ",
        "`priority`, `invalid`)",
        "values (#{address,jdbcType=VARCHAR}, #{shopId,jdbcType=BIGINT}, ",
        "#{name,jdbcType=VARCHAR}, #{senderName,jdbcType=VARCHAR}, ",
        "#{creatorId,jdbcType=BIGINT}, #{creatorName,jdbcType=VARCHAR}, ",
        "#{modifierId,jdbcType=BIGINT}, #{modifierName,jdbcType=VARCHAR}, ",
        "#{gmtCreate,jdbcType=TIMESTAMP}, #{gmtModified,jdbcType=TIMESTAMP}, ",
        "#{regionId,jdbcType=BIGINT}, #{senderMobile,jdbcType=VARCHAR}, ",
        "#{priority,jdbcType=INTEGER}, #{invalid,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(WarehousePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @InsertProvider(type=WarehousePoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(WarehousePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @SelectProvider(type=WarehousePoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sender_name", property="senderName", jdbcType=JdbcType.VARCHAR),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="region_id", property="regionId", jdbcType=JdbcType.BIGINT),
        @Result(column="sender_mobile", property="senderMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="priority", property="priority", jdbcType=JdbcType.INTEGER),
        @Result(column="invalid", property="invalid", jdbcType=JdbcType.TINYINT)
    })
    List<WarehousePo> selectByExample(WarehousePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `address`, `shop_id`, `name`, `sender_name`, `creator_id`, `creator_name`, ",
        "`modifier_id`, `modifier_name`, `gmt_create`, `gmt_modified`, `region_id`, `sender_mobile`, ",
        "`priority`, `invalid`",
        "from freight_warehouse",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="shop_id", property="shopId", jdbcType=JdbcType.BIGINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="sender_name", property="senderName", jdbcType=JdbcType.VARCHAR),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="region_id", property="regionId", jdbcType=JdbcType.BIGINT),
        @Result(column="sender_mobile", property="senderMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="priority", property="priority", jdbcType=JdbcType.INTEGER),
        @Result(column="invalid", property="invalid", jdbcType=JdbcType.TINYINT)
    })
    WarehousePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WarehousePoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") WarehousePo row, @Param("example") WarehousePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WarehousePoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") WarehousePo row, @Param("example") WarehousePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @UpdateProvider(type=WarehousePoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WarehousePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_warehouse
     *
     * @mbg.generated
     */
    @Update({
        "update freight_warehouse",
        "set `address` = #{address,jdbcType=VARCHAR},",
          "`shop_id` = #{shopId,jdbcType=BIGINT},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "`sender_name` = #{senderName,jdbcType=VARCHAR},",
          "`creator_id` = #{creatorId,jdbcType=BIGINT},",
          "`creator_name` = #{creatorName,jdbcType=VARCHAR},",
          "`modifier_id` = #{modifierId,jdbcType=BIGINT},",
          "`modifier_name` = #{modifierName,jdbcType=VARCHAR},",
          "`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP},",
          "`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP},",
          "`region_id` = #{regionId,jdbcType=BIGINT},",
          "`sender_mobile` = #{senderMobile,jdbcType=VARCHAR},",
          "`priority` = #{priority,jdbcType=INTEGER},",
          "`invalid` = #{invalid,jdbcType=TINYINT}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(WarehousePo row);
}