package cn.edu.xmu.oomall.freight.mapper.generator.po;

import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
@Builder
@Data
public class ExpressPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.bill_code
     *
     * @mbg.generated
     */
    private String billCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.shop_logistics_id
     *
     * @mbg.generated
     */
    private Long shopLogisticsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.sender_region_id
     *
     * @mbg.generated
     */
    private Long senderRegionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.sender_address
     *
     * @mbg.generated
     */
    private String senderAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.deliver_region_id
     *
     * @mbg.generated
     */
    private Long deliverRegionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.deliver_address
     *
     * @mbg.generated
     */
    private String deliverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.sender_name
     *
     * @mbg.generated
     */
    private String senderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.sender_mobile
     *
     * @mbg.generated
     */
    private String senderMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.deliver_name
     *
     * @mbg.generated
     */
    private String deliverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_express.deliver_mobile
     *
     * @mbg.generated
     */
    private String deliverMobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.id
     *
     * @return the value of freight_express.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.id
     *
     * @param id the value for freight_express.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.bill_code
     *
     * @return the value of freight_express.bill_code
     *
     * @mbg.generated
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.bill_code
     *
     * @param billCode the value for freight_express.bill_code
     *
     * @mbg.generated
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode == null ? null : billCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.shop_logistics_id
     *
     * @return the value of freight_express.shop_logistics_id
     *
     * @mbg.generated
     */
    public Long getShopLogisticsId() {
        return shopLogisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.shop_logistics_id
     *
     * @param shopLogisticsId the value for freight_express.shop_logistics_id
     *
     * @mbg.generated
     */
    public void setShopLogisticsId(Long shopLogisticsId) {
        this.shopLogisticsId = shopLogisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.sender_region_id
     *
     * @return the value of freight_express.sender_region_id
     *
     * @mbg.generated
     */
    public Long getSenderRegionId() {
        return senderRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.sender_region_id
     *
     * @param senderRegionId the value for freight_express.sender_region_id
     *
     * @mbg.generated
     */
    public void setSenderRegionId(Long senderRegionId) {
        this.senderRegionId = senderRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.sender_address
     *
     * @return the value of freight_express.sender_address
     *
     * @mbg.generated
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.sender_address
     *
     * @param senderAddress the value for freight_express.sender_address
     *
     * @mbg.generated
     */
    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress == null ? null : senderAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.deliver_region_id
     *
     * @return the value of freight_express.deliver_region_id
     *
     * @mbg.generated
     */
    public Long getDeliverRegionId() {
        return deliverRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.deliver_region_id
     *
     * @param deliverRegionId the value for freight_express.deliver_region_id
     *
     * @mbg.generated
     */
    public void setDeliverRegionId(Long deliverRegionId) {
        this.deliverRegionId = deliverRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.deliver_address
     *
     * @return the value of freight_express.deliver_address
     *
     * @mbg.generated
     */
    public String getDeliverAddress() {
        return deliverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.deliver_address
     *
     * @param deliverAddress the value for freight_express.deliver_address
     *
     * @mbg.generated
     */
    public void setDeliverAddress(String deliverAddress) {
        this.deliverAddress = deliverAddress == null ? null : deliverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.sender_name
     *
     * @return the value of freight_express.sender_name
     *
     * @mbg.generated
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.sender_name
     *
     * @param senderName the value for freight_express.sender_name
     *
     * @mbg.generated
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.sender_mobile
     *
     * @return the value of freight_express.sender_mobile
     *
     * @mbg.generated
     */
    public String getSenderMobile() {
        return senderMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.sender_mobile
     *
     * @param senderMobile the value for freight_express.sender_mobile
     *
     * @mbg.generated
     */
    public void setSenderMobile(String senderMobile) {
        this.senderMobile = senderMobile == null ? null : senderMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.deliver_name
     *
     * @return the value of freight_express.deliver_name
     *
     * @mbg.generated
     */
    public String getDeliverName() {
        return deliverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.deliver_name
     *
     * @param deliverName the value for freight_express.deliver_name
     *
     * @mbg.generated
     */
    public void setDeliverName(String deliverName) {
        this.deliverName = deliverName == null ? null : deliverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.status
     *
     * @return the value of freight_express.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.status
     *
     * @param status the value for freight_express.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.shop_id
     *
     * @return the value of freight_express.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.shop_id
     *
     * @param shopId the value for freight_express.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.creator_id
     *
     * @return the value of freight_express.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.creator_id
     *
     * @param creatorId the value for freight_express.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.creator_name
     *
     * @return the value of freight_express.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.creator_name
     *
     * @param creatorName the value for freight_express.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.modifier_id
     *
     * @return the value of freight_express.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.modifier_id
     *
     * @param modifierId the value for freight_express.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.modifier_name
     *
     * @return the value of freight_express.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.modifier_name
     *
     * @param modifierName the value for freight_express.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.gmt_create
     *
     * @return the value of freight_express.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.gmt_create
     *
     * @param gmtCreate the value for freight_express.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.gmt_modified
     *
     * @return the value of freight_express.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.gmt_modified
     *
     * @param gmtModified the value for freight_express.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_express.deliver_mobile
     *
     * @return the value of freight_express.deliver_mobile
     *
     * @mbg.generated
     */
    public String getDeliverMobile() {
        return deliverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_express.deliver_mobile
     *
     * @param deliverMobile the value for freight_express.deliver_mobile
     *
     * @mbg.generated
     */
    public void setDeliverMobile(String deliverMobile) {
        this.deliverMobile = deliverMobile == null ? null : deliverMobile.trim();
    }
}