package cn.edu.xmu.oomall.freight.mapper.generator.po;

import lombok.Builder;

import java.time.LocalDateTime;
@Builder

public class LogisticsPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.sn_pattern
     *
     * @mbg.generated
     */
    private String snPattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.secret
     *
     * @mbg.generated
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_logistics.logistics_class
     *
     * @mbg.generated
     */
    private String logisticsClass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.id
     *
     * @return the value of freight_logistics.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.id
     *
     * @param id the value for freight_logistics.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.name
     *
     * @return the value of freight_logistics.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.name
     *
     * @param name the value for freight_logistics.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.app_id
     *
     * @return the value of freight_logistics.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.app_id
     *
     * @param appId the value for freight_logistics.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.creator_id
     *
     * @return the value of freight_logistics.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.creator_id
     *
     * @param creatorId the value for freight_logistics.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.creator_name
     *
     * @return the value of freight_logistics.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.creator_name
     *
     * @param creatorName the value for freight_logistics.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.modifier_id
     *
     * @return the value of freight_logistics.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.modifier_id
     *
     * @param modifierId the value for freight_logistics.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.modifier_name
     *
     * @return the value of freight_logistics.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.modifier_name
     *
     * @param modifierName the value for freight_logistics.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.gmt_create
     *
     * @return the value of freight_logistics.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.gmt_create
     *
     * @param gmtCreate the value for freight_logistics.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.gmt_modified
     *
     * @return the value of freight_logistics.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.gmt_modified
     *
     * @param gmtModified the value for freight_logistics.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.sn_pattern
     *
     * @return the value of freight_logistics.sn_pattern
     *
     * @mbg.generated
     */
    public String getSnPattern() {
        return snPattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.sn_pattern
     *
     * @param snPattern the value for freight_logistics.sn_pattern
     *
     * @mbg.generated
     */
    public void setSnPattern(String snPattern) {
        this.snPattern = snPattern == null ? null : snPattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.secret
     *
     * @return the value of freight_logistics.secret
     *
     * @mbg.generated
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.secret
     *
     * @param secret the value for freight_logistics.secret
     *
     * @mbg.generated
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_logistics.logistics_class
     *
     * @return the value of freight_logistics.logistics_class
     *
     * @mbg.generated
     */
    public String getLogisticsClass() {
        return logisticsClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_logistics.logistics_class
     *
     * @param logisticsClass the value for freight_logistics.logistics_class
     *
     * @mbg.generated
     */
    public void setLogisticsClass(String logisticsClass) {
        this.logisticsClass = logisticsClass == null ? null : logisticsClass.trim();
    }
}