package cn.edu.xmu.oomall.freight.mapper.generator.po;

import lombok.Builder;

import java.time.LocalDateTime;
@Builder
public class ShopLogisticsPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.logistics_id
     *
     * @mbg.generated
     */
    private Long logisticsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.secret
     *
     * @mbg.generated
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.invalid
     *
     * @mbg.generated
     */
    private Byte invalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_shop_logistics.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.id
     *
     * @return the value of freight_shop_logistics.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.id
     *
     * @param id the value for freight_shop_logistics.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.shop_id
     *
     * @return the value of freight_shop_logistics.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.shop_id
     *
     * @param shopId the value for freight_shop_logistics.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.logistics_id
     *
     * @return the value of freight_shop_logistics.logistics_id
     *
     * @mbg.generated
     */
    public Long getLogisticsId() {
        return logisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.logistics_id
     *
     * @param logisticsId the value for freight_shop_logistics.logistics_id
     *
     * @mbg.generated
     */
    public void setLogisticsId(Long logisticsId) {
        this.logisticsId = logisticsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.secret
     *
     * @return the value of freight_shop_logistics.secret
     *
     * @mbg.generated
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.secret
     *
     * @param secret the value for freight_shop_logistics.secret
     *
     * @mbg.generated
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.creator_id
     *
     * @return the value of freight_shop_logistics.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.creator_id
     *
     * @param creatorId the value for freight_shop_logistics.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.creator_name
     *
     * @return the value of freight_shop_logistics.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.creator_name
     *
     * @param creatorName the value for freight_shop_logistics.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.modifier_id
     *
     * @return the value of freight_shop_logistics.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.modifier_id
     *
     * @param modifierId the value for freight_shop_logistics.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.modifier_name
     *
     * @return the value of freight_shop_logistics.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.modifier_name
     *
     * @param modifierName the value for freight_shop_logistics.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.gmt_create
     *
     * @return the value of freight_shop_logistics.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.gmt_create
     *
     * @param gmtCreate the value for freight_shop_logistics.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.gmt_modified
     *
     * @return the value of freight_shop_logistics.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.gmt_modified
     *
     * @param gmtModified the value for freight_shop_logistics.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.invalid
     *
     * @return the value of freight_shop_logistics.invalid
     *
     * @mbg.generated
     */
    public Byte getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.invalid
     *
     * @param invalid the value for freight_shop_logistics.invalid
     *
     * @mbg.generated
     */
    public void setInvalid(Byte invalid) {
        this.invalid = invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_shop_logistics.priority
     *
     * @return the value of freight_shop_logistics.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_shop_logistics.priority
     *
     * @param priority the value for freight_shop_logistics.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}