package cn.edu.xmu.oomall.freight.mapper.generator.po;

import lombok.Builder;

import java.time.LocalDateTime;
@Builder
public class WarehousePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.sender_name
     *
     * @mbg.generated
     */
    private String senderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.region_id
     *
     * @mbg.generated
     */
    private Long regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.sender_mobile
     *
     * @mbg.generated
     */
    private String senderMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.priority
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse.invalid
     *
     * @mbg.generated
     */
    private Byte invalid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.id
     *
     * @return the value of freight_warehouse.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.id
     *
     * @param id the value for freight_warehouse.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.address
     *
     * @return the value of freight_warehouse.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.address
     *
     * @param address the value for freight_warehouse.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.shop_id
     *
     * @return the value of freight_warehouse.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.shop_id
     *
     * @param shopId the value for freight_warehouse.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.name
     *
     * @return the value of freight_warehouse.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.name
     *
     * @param name the value for freight_warehouse.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.sender_name
     *
     * @return the value of freight_warehouse.sender_name
     *
     * @mbg.generated
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.sender_name
     *
     * @param senderName the value for freight_warehouse.sender_name
     *
     * @mbg.generated
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.creator_id
     *
     * @return the value of freight_warehouse.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.creator_id
     *
     * @param creatorId the value for freight_warehouse.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.creator_name
     *
     * @return the value of freight_warehouse.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.creator_name
     *
     * @param creatorName the value for freight_warehouse.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.modifier_id
     *
     * @return the value of freight_warehouse.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.modifier_id
     *
     * @param modifierId the value for freight_warehouse.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.modifier_name
     *
     * @return the value of freight_warehouse.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.modifier_name
     *
     * @param modifierName the value for freight_warehouse.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.gmt_create
     *
     * @return the value of freight_warehouse.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.gmt_create
     *
     * @param gmtCreate the value for freight_warehouse.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.gmt_modified
     *
     * @return the value of freight_warehouse.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.gmt_modified
     *
     * @param gmtModified the value for freight_warehouse.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.region_id
     *
     * @return the value of freight_warehouse.region_id
     *
     * @mbg.generated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.region_id
     *
     * @param regionId the value for freight_warehouse.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.sender_mobile
     *
     * @return the value of freight_warehouse.sender_mobile
     *
     * @mbg.generated
     */
    public String getSenderMobile() {
        return senderMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.sender_mobile
     *
     * @param senderMobile the value for freight_warehouse.sender_mobile
     *
     * @mbg.generated
     */
    public void setSenderMobile(String senderMobile) {
        this.senderMobile = senderMobile == null ? null : senderMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.priority
     *
     * @return the value of freight_warehouse.priority
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.priority
     *
     * @param priority the value for freight_warehouse.priority
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse.invalid
     *
     * @return the value of freight_warehouse.invalid
     *
     * @mbg.generated
     */
    public Byte getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse.invalid
     *
     * @param invalid the value for freight_warehouse.invalid
     *
     * @mbg.generated
     */
    public void setInvalid(Byte invalid) {
        this.invalid = invalid;
    }
}